### ISSUE TITLE
请问这个程序基于原来的程序有什么提升吗，在哪方面体现出来了呢？

### ISSUE THREAD

**Issue by Flee-postgra** [peteryuan123/HPGO-ORBSLAM3#1]
May I ask if there are any improvements to this program based on the original one, and in what aspects have they been reflected?

**Comment by peteryuan123** [comment]
In this program, we can handle the situation where you have **multiple** trajectory segments caused by "tracking lost" and these segments could be in different scale. When a loop closure is triggered, the system will use HPGO to build a global-scale-consistent trajectory. 

However, this program is a very rough demo currently. It has some limitations:
1. It can only work in planar case (since we use one-point ransac to estimate relative orientation in re-initialization phase)
2. In some scenarios, the solution of HPGO is not unique, which you can refer to the paper.

If you have interest, please refer to the _LostManager.cc_ in _src_ and function _MonocularInitializationNew()_  in Tracking.cc , this is the core algorithm of the repository.

In general, the contribution is mainly to handle the situation shown in the demo.
Please forgive me that I don't have time to refine the readme and code structure. Will do it later:)

**Comment by Flee-postgra** [comment]
thanks for your answer, your are great!
